apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld

spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld

    spec:
      containers:
        - name: helloworld
          image: au.icr.io/hello_world_deepika/helloworld
          imagePullPolicy: Always
          ports:
          - containerPort: 5000